useTabs: true
singleQuote: true
trailingComma: none
printWidth: 100
plugins:
  - '@ianvs/prettier-plugin-sort-imports'
importOrder:
  - '<TYPES>^(node:)'
  - '<TYPES>'
  - '<TYPES>^[.]'
  - '<BUILTIN_MODULES>'
  - '<THIRD_PARTY_MODULES>'
  - '^[.]'
importOrderParserPlugins:
  - 'typescript'
  - 'jsx'
  - 'decorators'
