#!/usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)
git_branch=$(git rev-parse --abbrev-ref HEAD)
git_root=$(git rev-parse --show-toplevel)
git_version=$(git describe --tags --abbrev=0)
version=${git_version#v}

major=$(echo "${version}" | cut -d . -f1)
minor=$(echo "${version}" | cut -d . -f2)
patch=$(echo "${version}" | cut -d . -f3)
case "${1-patch}" in
    major) major=$((major + 1)) ;;
    minor) minor=$((minor + 1)) ;;
    *) patch=$((patch + 1)) ;;
esac
next_version="${major}.${minor}.${patch}"

echo "${version} -> ${next_version}"

echo "bumping web"
cd "${git_root}"
npm version "${next_version}" --no-git-tag-version
git add package-lock.json
git add package.json

echo "bumping nix"
cd "${git_root}"
nix-update --flake --version "${next_version}" default
git add flake.nix

echo "committing"
git commit -m "bump: v${version} -> v${next_version}"
git tag -a "v${next_version}" -m "bump: v${version} -> v${next_version}"

echo "bump successful, please push:"
echo "${bold}git push --atomic origin ${git_branch} \"v${next_version}\"${normal}"