name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: spotdemo4/nix-init@0c8446eb257c25d2ffca5d6b907ea8a7b9de9e02 # v1.32.0

      - name: Check
        run: nix flake check
