name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - run: git push origin "${{ github.ref_name }}:latest" --force
