name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: spotdemo4/better-checkout@48475b2dda4ef6945cb56e846429b43799121549 # v0.5.1
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Release
        uses: spotdemo4/nix-flake-release@7bbb4f6af968cb81b3cc36f906cd3c8e15a29285 # v0.11.5
        with:
          github_token: ${{ steps.checkout.outputs.token }}
